{{- if gt (len .Values.awsSecrets) 0 }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-{{ include "tacbot.name" . }}
spec:
  provider: aws
  parameters: 
    objects: |
      {{- range $key, $value := .Values.awsSecrets }}
      - objectName: {{ $value.name }}
        objectType: "secretsmanager"
        jmesPath:
        {{- range $key1, $value1 := $value.keys }}
          - path: {{ $value1 }}
            objectAlias: {{ $value1 }}
        {{- end }}
      {{- end }}
  # Create k8s secret. It requires volume mount first in the pod and then sync.
  secretObjects:          
    {{- range $key, $value := .Values.awsSecrets }}
    - secretName: tacbot-backend
      type: Opaque
      data:
        {{- range $key1, $value1 := $value.keys }} 
        - objectName: {{ $value1 }}
          key: {{ $value1 }}
        {{- end }}
    {{- end }}
{{- end }}