apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    {{- include "tacbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    {{- include "tacbot.selectorLabels" . | nindent 4 }}
